scenario_id: S2_edge_cloud
workload:
  num_requests: 200
nodes:
  cloud_p0:
    gpu:
      name: A100_80GB
      vram_total_gb: 80
      vram_free_gb: 55
    running_prefill: 3
    queued_prefill: 2
    tags:
      tier: cloud
      role: prefill
  cloud_d0:
    gpu:
      name: A100_80GB
      vram_total_gb: 80
      vram_free_gb: 45
    running_decode: 5
    queued_decode: 5
    tags:
      tier: cloud
      role: decode
  edge_d0:
    gpu:
      name: L4_24GB
      vram_total_gb: 24
      vram_free_gb: 14
    running_decode: 3
    queued_decode: 6
    tags:
      tier: edge
      role: decode
  edge_d1:
    gpu:
      name: L4_24GB
      vram_total_gb: 24
      vram_free_gb: 12
    running_decode: 2
    queued_decode: 7
    tags:
      tier: edge
      role: decode
network:
  default_util: 0.2
  links:
  - src: cloud_p0
    dst: cloud_d0
    bandwidth_Gbps: 200.0
    rtt_ms: 0.25
  - src: cloud_d0
    dst: cloud_p0
    bandwidth_Gbps: 200.0
    rtt_ms: 0.25
  - src: cloud_p0
    dst: edge_d0
    bandwidth_Gbps: 5.0
    rtt_ms: 20.0
  - src: edge_d0
    dst: cloud_p0
    bandwidth_Gbps: 5.0
    rtt_ms: 20.0
  - src: cloud_p0
    dst: edge_d1
    bandwidth_Gbps: 5.0
    rtt_ms: 20.0
  - src: edge_d1
    dst: cloud_p0
    bandwidth_Gbps: 5.0
    rtt_ms: 20.0
  - src: cloud_d0
    dst: edge_d0
    bandwidth_Gbps: 5.0
    rtt_ms: 20.0
  - src: edge_d0
    dst: cloud_d0
    bandwidth_Gbps: 5.0
    rtt_ms: 20.0
  - src: cloud_d0
    dst: edge_d1
    bandwidth_Gbps: 5.0
    rtt_ms: 20.0
  - src: edge_d1
    dst: cloud_d0
    bandwidth_Gbps: 5.0
    rtt_ms: 20.0
  - src: edge_d0
    dst: edge_d1
    bandwidth_Gbps: 10.0
    rtt_ms: 1.0
  - src: edge_d1
    dst: edge_d0
    bandwidth_Gbps: 10.0
    rtt_ms: 1.0
  util_by_pair: {}
